# Generated by Django 5.2.6 on 2026-01-20 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAllMutedFiledSwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muteAddProperty', models.BooleanField(verbose_name=False)),
                ('muteAddServices', models.BooleanField(verbose_name=False)),
                ('muteEdit', models.BooleanField(verbose_name=False)),
                ('muteNotifications', models.BooleanField(verbose_name=False)),
                ('muteNotificationManageMent', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.AddField(
            model_name='categoryofservices',
            name='servise_provider_mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingproperty',
            name='Ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingproperty',
            name='StayLongAllow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingproperty',
            name='filterWater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingproperty',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingproperty',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingproperty',
            name='securityCam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingproperty',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='Owner',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.IntegerField(default=1)),
                ('nights', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.listingproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.customuser')),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.CreateModel(
            name='HostLoginDetailsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_names', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='host_image_login')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('login_count', models.IntegerField(default=1)),
                ('status_login', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, default='hostImage/default_host.png', null=True, upload_to='hostImage/')),
                ('govt_id_type', models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('pan', 'PAN Card')], max_length=50, null=True)),
                ('govt_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to='app.customuser')),
            ],
            options={
                'verbose_name': 'Host Profile',
                'verbose_name_plural': 'Host Profiles',
            },
        ),
        migrations.AlterField(
            model_name='listingproperty',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app.hostprofile'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('captured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.hostprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.listingproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='AddToWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='app.listingproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='app.customuser')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
