# Generated by Django 5.2.6 on 2026-02-06 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_refund_options_refund_bank_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsForHostByAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_properties', models.IntegerField(default=0)),
                ('commission_per_property', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='app.hostprofile')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('host', 'month', 'year')},
            },
        ),
    ]
